apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-maibot-scripts
  namespace: {{ .Release.Namespace }}
data:
  # core
  k8s-init.sh: |
    {{ .Files.Get "files/k8s-init.sh" | nindent 4 }}
  # core的初始化容器
  {{- if .Values.core.setup_default_plugins }}
  setup-plugins.py: |
    {{ .Files.Get "files/setup-plugins.py" | nindent 4 }}
  {{- end }}
