apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-maibot-scripts
  namespace: {{ .Release.Namespace }}
data:
  # core
  volume-linker.sh: |
    {{ .Files.Get "files/volume-linker.sh" | nindent 4 }}
  # core的初始化容器
  setup-plugins.py: |
    {{ .Files.Get "files/setup-plugins.py" | nindent 4 }}
