{{- if or .Release.IsInstall .Values.config.enable_config_override }}
# 渲染规则：
# 初次安装，或配置了覆盖规则
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-maibot-core-model-config
  namespace: {{ .Release.Namespace }}
data:
  model_config.toml: |
    {{ .Values.config.core_model_config | nindent 4 }}
{{- end }}
